# This is a basic workflow to help you get started with Actions

name: SpotBugs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  spotbugs:
    uses: mrjonstrong/spotbugs-action/.github/workflows/spotbugs.yml@327e35e692e55b0b0f6324f5d2cf731ce1a23cb4
