name: SpotBugs
on:
  push:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    name: SpotBugs
    steps:
      - name: Spot Bugs
        uses: mrjonstrong/spotbugs-action@e8fa8ebab45dd9e54d830ebe2fc2bbffb5971035
